{% set name = "kenlm" %}
{% set commit = "e504a4d61c413873e7d5f13d8ac4890bd4dae36c" %}
{% set version = commit[:7] %}
{% set sha1value = commit %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/kpu/kenlm
  git_rev: {{ commit }}
  sha1: {{ sha1value }}

build:
  skip: True  # [not linux64]
  number: 0
  script_env:
    - KENLM_MAX_ORDER=7

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - libgomp # openmp
  host:
    - pip
    - python
    - boost-cpp
    - eigen
    - zlib
    - bzip2
    - xz
  run:
    - python
    - boost-cpp
    - eigen
    - zlib
    - bzip2
    - xz

test:
  imports:
    - kenlm
  requires:
    - pip
  commands:
    - pip check
    - command -V lmplz
    - command -V filter
    - command -V build_binary

about:
  home: https://github.com/kpu/kenlm
  summary: Faster and Smaller Language Model Queries
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cgr71ii
